id: P005544
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5036
  title: གསོ་རིག་རྒྱུད་བཞི།
  author: ''
  volumes:
    007963159ba24753badc07d2ae2cb928:
      image_group_id: I3CN5038
      title: ''
      volume_number: 1
      total_pages: 627
